server:
  port: 8084
feign:
  okhttp:
    enabled: true
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  swagger:
    title: 用户服务接口文档
    description: "用户服务接口文档"
    package: com.hmall.user.controller
  db:
    database: hm-user
